config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:create, :new]
      resources :likes, only: [:create]
    end
  end
  
  # Defines the root path route ("/")
  root to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_comments_counter

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts_counter

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def recent_comments(max = 5)
    comments.order(created_at: :desc).limit(max)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts(max = 3)
    posts.order(created_at: :desc).limit(max)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.new(post_params)
    @comment.post_id = params[:post_id]
    @comment.save
    redirect_to user_post_path(@comment.author_id, @comment.post_id)
  end

  def new
    @comment = Comment.new
  end

  private

  def post_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    like = Like.new(author_id: current_user.id, post_id: post.id)

    if like.save
      flash[:success] = 'Liked'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to "/users/#{post.author.id}/posts/#{post.id}"
  end

  private

  def like_params
    params.require(:like).permit(:post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @user_posts = @user.posts.order('created_at DESC')
  end

  def show
    @current_post = Post.find(params[:id])
    @current_user = current_user
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to user_posts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<%= form_with model: Comment.new, url: user_post_comments_path(post_id: params[:post_id], user_id: params[:user_id]), class: 'form-comment' do |f| %>
  <div class="form-comment-container">
    <%= f.text_area :text, rows: 5, placeholder: 'Leave your comment here ...', class: 'f-text-area' %>
  </div>

  <div class="form-submit">
    <%= f.submit 'Add a new comment', class: 'submit-comment' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/partials/_comment.html.erb
<p class="p-comment-container">
  <span><%= comment.author.name %></span>
  <%= comment.text %>
</p>

app/views/partials/_comment_form.html.erb
<%= form_with model: Comment.new, url: user_post_comments_path(post_id: post_id, user_id: user_id), class: 'form-comment' do |f| %>
  <div class="form-comment-container">
    <%= f.text_area :text, rows: 5, placeholder: 'Leave your comment here ...', class: 'f-text-area' %>
  </div>

  <div class="form-submit">
    <%= f.submit 'Add a new comment', class: 'submit-comment' %>
  </div>
<% end %>

app/views/partials/_comments.html.erb
<p class="p-comment-container">
  <span><%= comment.author.name %></span>
  <%= comment.text.truncate_words(10) %>
</p>

app/views/partials/_post.html.erb
<div class="p-post-container">
  <h2>
    <%= post.title %> by <%= post.author.name %>
    <span class="like-span">
      Comments: <%= post.comments_counter %> |  Likes: <%= post.likes_counter %>
    </span>
  </h2>

  <p><%= post.text %></p>

  <%= button_to 'Like',
    user_post_likes_path(post_id: post.id),
    class: 'button-like'
  %>
</div>

app/views/partials/_post_form.html.erb
<%= form_with model: @post, url: user_posts_url, class: 'post-form-container' do |f| %>
  <div class="title-field-container">
    <%= f.label :title, class: 'title-label' %>
    <%= f.text_field :title, placeholder: 'Title', class: 'title-text-field' %>
  </div>

  <div class="content-container">
    <%= f.label :content, class: 'content-label' %>
    <%= f.text_area :text, rows: 5, placeholder: 'Content...', class: 'content-text-area' %>
  </div>

  <div class="submit-btn-container">
    <%= f.submit 'Create post', class: 'submit-btn' %>
  </div>
<% end %>

app/views/partials/_posts.html.erb
<div class="p-post-container">
  <%= link_to user_post_path(user_id: @user.id, id: post.id) do %>
    <h2><%= post.title %></h2>
    <p><%= post.text.truncate_words(20) %></p>
  <% end %>
  <p class="like-par">
    Comments: <%= post.comments_counter %>  | Likes: <%= post.likes_counter %>
  </p>
</div>

app/views/partials/_user.html.erb
<div class="p-user-container">
  <div class="img-container">
    <img class="post-img-user" src="<%= user.photo %>" alt="user image"/>
  </div>  
  <div class="info-container">
    <%= link_to user_path(user.id) do %>
      <h2><%= user.name %></h2>
      <p>Number of posts: <%= user.posts.count %></p>
    <% end %>
  </div>  
</div>

app/views/posts/index.html.erb
<%= render 'partials/user', user: @user %>

<div class="post-create-btn-container">
  <button type="button" class="post-create-btn">
    <%= link_to "Create a new post", new_user_post_path %>
  </button>
</div>

<% if @user.recent_posts.length > 0 %>
  <% @user_posts.each do |post| %>
    <%= render partial: 'partials/posts', locals: { post: post } %>
    <% if post.comments_counter > 0 %>
      <div class="comment">
        <% post.recent_comments.each do |comment| %>
          <%= render partial: 'partials/comments', locals: { comment: comment } %>
        <% end %>
      </div>
    <% else %>
      <div></div>
    <% end %>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<%= render partial: 'partials/post_form' %>

app/views/posts/show.html.erb
<%= render partial: 'partials/post', locals: { post: @current_post } %>
<% if @current_post.comments_counter > 0 %>
  <div class="comment">
    <% @current_post.comments.each do |comment| %>
      <%= render partial: 'partials/comments', locals: { comment: comment } %>
    <% end %>
  </div>
<% else %>
  <div></div>
<% end %>
<%= render partial: 'partials/comment_form', locals: { post_id: @current_post.id, user_id: @current_user.id } %>

app/views/users/index.html.erb
<%= render partial: 'partials/user', collection: @users, as: :user %>

app/views/users/show.html.erb
<%= render 'partials/user', user: @user %>
<div class="user-container">
  <h2>Bio</h2>
  <p>
    <%= @user.bio %>  
  </p>
</div>
<% if @user.recent_posts.length > 0 %>
  <% @user.recent_posts.each do |post| %>
    <%= render partial: 'partials/posts', locals: { post: post } %>
  <% end %>
  <div class="btn-container">
    <button type="button">
      <%= link_to "See all posts", user_posts_path(@user) %>
    </button>
  </div>
<% end %>